# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-12 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('userId', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('working_directory', models.CharField(max_length=90)),
            ],
        ),
    ]
